# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in the Android SDK tools proguard-defaults.txt.

# Keep UniFFI/JNA generated code — it uses reflection
-keep class com.sun.jna.** { *; }
-keep class * implements com.sun.jna.** { *; }

# Keep our Rust FFI binding classes (generated by uniffi-bindgen)
-keep class uniffi.sofamsg.** { *; }

# Don't warn about JNA internals
-dontwarn com.sun.jna.**
