#![allow(clippy::all)]

//! SofaMsg / SilentBell — UniFFI FFI layer
//!
//! This crate is the bridge between the Rust core library and the
//! Kotlin (Android) / Swift (iOS) frontends.  It implements the types
//! and functions declared in `sofamsg.udl` using simple, FFI-safe
//! wrapper types.
//!
//! # Architecture
//!
//! ```text
//!  Kotlin / Swift
//!       │
//!  ─────┼───── UniFFI-generated bindings (.kt / .swift)
//!       │
//!  silentbell_ffi          ← this crate (cdylib)
//!       │
//!  silentbell_core         ← crypto, identity, vault, storage, decoy, invite
//!  silentbell_p2p          ← networking, queues
//! ```

use std::sync::Arc;

// Pull in the scaffolding generated by build.rs from sofamsg.udl.
uniffi::include_scaffolding!("sofamsg");

// ── Error type ──────────────────────────────────────────────────

/// FFI-safe error enum.  Maps to the `[Error] enum SofaMsgError` in
/// the UDL.
#[derive(Debug, thiserror::Error)]
pub enum SofaMsgError {
    #[error("Salt must be exactly 16 bytes")]
    InvalidSaltLength,

    #[error("Seed must be exactly 32 bytes")]
    InvalidSeedLength,

    #[error("Key bytes must be exactly 32 bytes")]
    InvalidKeyLength,

    #[error("Vault encryption failed")]
    VaultEncryptionFailed,

    #[error("Vault decryption failed")]
    VaultDecryptionFailed,

    #[error("Failed to open encrypted database")]
    DatabaseOpenFailed,

    #[error("Failed to create database schema")]
    DatabaseSchemaFailed,

    #[error("Database operation failed")]
    DatabaseOperationFailed,

    #[error("Invite operation failed")]
    InviteFailed,
}

// ── Identity ────────────────────────────────────────────────────

/// FFI-safe result of identity creation.
/// Maps to the `dictionary IdentityResult` in the UDL.
pub struct IdentityResult {
    pub account_id: String,
    pub public_key_hex: String,
}

/// Opaque handle wrapping an Ed25519 `Keypair` from silentbell_core.
pub struct FfiKeypair {
    inner: silentbell_core::Keypair,
}

impl FfiKeypair {
    /// Generate a fresh Ed25519 keypair.
    pub fn generate() -> Self {
        FfiKeypair {
            inner: silentbell_core::Keypair::generate(),
        }
    }

    /// Hex-encoded 32-byte public (verifying) key.
    pub fn public_key_hex(&self) -> String {
        hex::encode(self.inner.public_key_bytes())
    }

    /// Derive the `sb_`-prefixed account ID.
    pub fn account_id(&self) -> String {
        silentbell_core::derive_account_id(&self.inner)
    }
}

// ── Vault ───────────────────────────────────────────────────────

/// Opaque handle wrapping a `VaultKey` (Argon2-derived 256-bit key).
pub struct FfiVaultKey {
    inner: silentbell_core::VaultKey,
}

impl FfiVaultKey {
    /// Derive a vault key from a user PIN and 16-byte salt.
    pub fn derive(pin: String, salt: Vec<u8>) -> Result<Self, SofaMsgError> {
        let salt_arr: [u8; 16] = salt
            .try_into()
            .map_err(|_| SofaMsgError::InvalidSaltLength)?;

        let key = silentbell_core::derive_key(&pin, &salt_arr);
        Ok(FfiVaultKey { inner: key })
    }

    /// Hex representation of the key (used for SQLCipher PRAGMA).
    pub fn as_hex(&self) -> String {
        self.inner.as_hex()
    }
}

/// Encrypt plaintext with the given vault key.
pub fn vault_encrypt(key: Arc<FfiVaultKey>, plaintext: Vec<u8>) -> Result<Vec<u8>, SofaMsgError> {
    Ok(silentbell_core::encrypt(&key.inner, &plaintext))
}

/// Decrypt a blob produced by `vault_encrypt`.
pub fn vault_decrypt(key: Arc<FfiVaultKey>, blob: Vec<u8>) -> Result<Vec<u8>, SofaMsgError> {
    Ok(silentbell_core::decrypt(&key.inner, &blob))
}

// ── Storage ─────────────────────────────────────────────────────

/// FFI-safe message record. Maps to `dictionary FfiStoredMessage`.
pub struct FfiStoredMessage {
    pub id: i64,
    pub peer_account_id: String,
    pub body: String,
    pub sent_at: i64,
    pub is_outgoing: bool,
}

/// Opaque handle wrapping a `rusqlite::Connection` opened with
/// SQLCipher encryption.
pub struct FfiDatabase {
    conn: std::sync::Mutex<rusqlite::Connection>,
}

impl FfiDatabase {
    /// Open (or create) an encrypted database at `path`.
    pub fn open(path: String, key: Arc<FfiVaultKey>) -> Result<Self, SofaMsgError> {
        let conn = silentbell_core::open_encrypted_db(&path, &key.inner)
            .map_err(|_| SofaMsgError::DatabaseOpenFailed)?;
        Ok(FfiDatabase {
            conn: std::sync::Mutex::new(conn),
        })
    }

    /// Create tables if they do not exist.
    pub fn ensure_schema(&self) -> Result<(), SofaMsgError> {
        let conn = self.conn.lock().expect("database mutex poisoned");
        silentbell_core::ensure_schema(&conn).map_err(|_| SofaMsgError::DatabaseSchemaFailed)
    }

    /// Insert a message into the encrypted database.
    pub fn insert_message(
        &self,
        peer_account_id: String,
        body: String,
        sent_at: i64,
        is_outgoing: bool,
    ) -> Result<i64, SofaMsgError> {
        let conn = self.conn.lock().expect("database mutex poisoned");
        silentbell_core::insert_message(&conn, &peer_account_id, &body, sent_at, is_outgoing)
            .map_err(|_| SofaMsgError::DatabaseOperationFailed)
    }

    /// Retrieve all messages for a given peer.
    pub fn get_messages(
        &self,
        peer_account_id: String,
    ) -> Result<Vec<FfiStoredMessage>, SofaMsgError> {
        let conn = self.conn.lock().expect("database mutex poisoned");
        let msgs = silentbell_core::get_messages(&conn, &peer_account_id)
            .map_err(|_| SofaMsgError::DatabaseOperationFailed)?;

        Ok(msgs
            .into_iter()
            .map(|m| FfiStoredMessage {
                id: m.id,
                peer_account_id: m.peer_account_id,
                body: m.body,
                sent_at: m.sent_at,
                is_outgoing: m.is_outgoing,
            })
            .collect())
    }

    /// Retrieve the most recent conversations.
    pub fn get_recent_conversations(
        &self,
        limit: u32,
    ) -> Result<Vec<FfiStoredMessage>, SofaMsgError> {
        let conn = self.conn.lock().expect("database mutex poisoned");
        let convos = silentbell_core::get_recent_conversations(&conn, limit)
            .map_err(|_| SofaMsgError::DatabaseOperationFailed)?;

        Ok(convos
            .into_iter()
            .map(|m| FfiStoredMessage {
                id: m.id,
                peer_account_id: m.peer_account_id,
                body: m.body,
                sent_at: m.sent_at,
                is_outgoing: m.is_outgoing,
            })
            .collect())
    }

    /// Delete a message by ID.
    pub fn delete_message(&self, message_id: i64) -> Result<bool, SofaMsgError> {
        let conn = self.conn.lock().expect("database mutex poisoned");
        silentbell_core::delete_message(&conn, message_id)
            .map_err(|_| SofaMsgError::DatabaseOperationFailed)
    }

    /// Pad database with chaff blocks.
    pub fn pad_chaff(&self, db_path: String) -> Result<u32, SofaMsgError> {
        let conn = self.conn.lock().expect("database mutex poisoned");
        silentbell_core::pad_chaff(&conn, &db_path)
            .map_err(|_| SofaMsgError::DatabaseOperationFailed)
    }

    /// Count current chaff blocks.
    pub fn chaff_count(&self) -> Result<u32, SofaMsgError> {
        let conn = self.conn.lock().expect("database mutex poisoned");
        silentbell_core::chaff_count(&conn).map_err(|_| SofaMsgError::DatabaseOperationFailed)
    }
}

// ── Decoy ───────────────────────────────────────────────────────

/// FFI-safe decoy message.
pub struct FfiDecoyMessage {
    pub body: String,
    pub is_outgoing: bool,
    pub seconds_ago: u64,
}

/// FFI-safe decoy conversation.
pub struct FfiDecoyConversation {
    pub peer_account_id: String,
    pub peer_name: String,
    pub messages: Vec<FfiDecoyMessage>,
}

/// Generate deterministic decoy conversations from a 32-byte seed.
pub fn generate_decoy_conversations(
    seed: Vec<u8>,
) -> Result<Vec<FfiDecoyConversation>, SofaMsgError> {
    let seed_arr: [u8; 32] = seed
        .try_into()
        .map_err(|_| SofaMsgError::InvalidSeedLength)?;

    let convos = silentbell_core::generate_decoy_content(&seed_arr);

    Ok(convos
        .into_iter()
        .map(|c| FfiDecoyConversation {
            peer_account_id: c.peer_account_id,
            peer_name: c.peer_name,
            messages: c
                .messages
                .into_iter()
                .map(|m| FfiDecoyMessage {
                    body: m.body,
                    is_outgoing: m.is_outgoing,
                    seconds_ago: m.seconds_ago,
                })
                .collect(),
        })
        .collect())
}

// ── Queue ID & Invitations ──────────────────────────────────────

/// Derive Queue ID from 32-byte public key.
pub fn derive_queue_id(public_key_bytes: Vec<u8>) -> Result<String, SofaMsgError> {
    let key_arr: [u8; 32] = public_key_bytes
        .try_into()
        .map_err(|_| SofaMsgError::InvalidKeyLength)?;
    let queue = silentbell_p2p::QueueId::from_public_key(&key_arr);
    Ok(queue.as_str().to_string())
}

/// FFI-safe invitation payload.
pub struct FfiInvitePayload {
    pub account_id: String,
    pub public_key_b58: String,
    pub queue_id_b58: String,
    pub display_name: Option<String>,
    pub version: u8,
}

impl From<silentbell_core::invite::InvitePayload> for FfiInvitePayload {
    fn from(p: silentbell_core::invite::InvitePayload) -> Self {
        FfiInvitePayload {
            account_id: p.account_id,
            public_key_b58: p.public_key_b58,
            queue_id_b58: p.queue_id_b58,
            display_name: p.display_name,
            version: p.version,
        }
    }
}

impl From<FfiInvitePayload> for silentbell_core::invite::InvitePayload {
    fn from(p: FfiInvitePayload) -> Self {
        silentbell_core::invite::InvitePayload {
            account_id: p.account_id,
            public_key_b58: p.public_key_b58,
            queue_id_b58: p.queue_id_b58,
            display_name: p.display_name,
            version: p.version,
        }
    }
}

pub fn create_invite(
    public_key_bytes: Vec<u8>,
    queue_id_bytes: Vec<u8>,
    display_name: Option<String>,
) -> Result<FfiInvitePayload, SofaMsgError> {
    let key_arr: [u8; 32] = public_key_bytes
        .try_into()
        .map_err(|_| SofaMsgError::InvalidKeyLength)?;
    let queue_arr: [u8; 32] = queue_id_bytes
        .try_into()
        .map_err(|_| SofaMsgError::InvalidKeyLength)?;

    let payload = silentbell_core::invite::InvitePayload::new(&key_arr, &queue_arr, display_name);
    Ok(payload.into())
}

pub fn invite_to_uri(invite: FfiInvitePayload) -> Result<String, SofaMsgError> {
    let payload: silentbell_core::invite::InvitePayload = invite.into();
    Ok(payload.to_uri())
}

pub fn invite_from_uri(uri: String) -> Result<FfiInvitePayload, SofaMsgError> {
    let payload = silentbell_core::invite::InvitePayload::from_uri(&uri)
        .map_err(|_| SofaMsgError::InviteFailed)?;
    Ok(payload.into())
}

pub fn invite_to_qr_data(invite: FfiInvitePayload) -> Result<Vec<u8>, SofaMsgError> {
    let payload: silentbell_core::invite::InvitePayload = invite.into();
    payload.to_qr_data().map_err(|_| SofaMsgError::InviteFailed)
}

pub fn invite_from_qr_data(data: Vec<u8>) -> Result<FfiInvitePayload, SofaMsgError> {
    let payload = silentbell_core::invite::InvitePayload::from_qr_data(&data)
        .map_err(|_| SofaMsgError::InviteFailed)?;
    Ok(payload.into())
}

pub fn invite_validate(invite: FfiInvitePayload) -> Result<bool, SofaMsgError> {
    let payload: silentbell_core::invite::InvitePayload = invite.into();
    Ok(payload.validate().is_ok())
}

// ── Top-level convenience ───────────────────────────────────────

/// One-shot identity creation.
pub fn create_new_identity() -> IdentityResult {
    let (keypair, account_id) = silentbell_core::create_new_identity();
    IdentityResult {
        account_id,
        public_key_hex: hex::encode(keypair.public_key_bytes()),
    }
}

// ── Tests ───────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identity_result_has_expected_format() {
        let result = create_new_identity();
        assert!(result.account_id.starts_with("sb_"));
        assert_eq!(result.public_key_hex.len(), 64);
    }

    #[test]
    fn ffi_keypair_roundtrip() {
        let kp = FfiKeypair::generate();
        let hex = kp.public_key_hex();
        let id = kp.account_id();
        assert_eq!(hex.len(), 64);
        assert!(id.starts_with("sb_"));
    }

    #[test]
    fn vault_key_derive_rejects_bad_salt() {
        let result = FfiVaultKey::derive("1234".into(), vec![0u8; 15]);
        assert!(result.is_err());
    }

    #[test]
    fn vault_encrypt_decrypt_roundtrip() {
        let key = Arc::new(FfiVaultKey::derive("1234".into(), vec![7u8; 16]).unwrap());
        let plaintext = b"hello sofamsg ffi".to_vec();
        let blob = vault_encrypt(key.clone(), plaintext.clone()).unwrap();
        let recovered = vault_decrypt(key, blob).unwrap();
        assert_eq!(recovered, plaintext);
    }

    #[test]
    fn decoy_rejects_bad_seed() {
        let result = generate_decoy_conversations(vec![0u8; 31]);
        assert!(result.is_err());
    }

    #[test]
    fn decoy_generates_valid_content() {
        let convos = generate_decoy_conversations(vec![42u8; 32]).unwrap();
        assert!(convos.len() >= 3 && convos.len() <= 5);
        for c in &convos {
            assert!(c.peer_account_id.starts_with("sb_"));
            assert!(!c.peer_name.is_empty());
            assert!(c.messages.len() >= 4);
        }
    }

    #[test]
    fn database_operations_and_chaff() {
        let key = Arc::new(FfiVaultKey::derive("1234".into(), vec![1u8; 16]).unwrap());
        let mut path_buf = std::env::temp_dir();
        path_buf.push("sofamsg_ffi_storage_test.db");
        let path = path_buf.to_string_lossy().into_owned();
        let _ = std::fs::remove_file(&path);

        let db = FfiDatabase::open(path.clone(), key).unwrap();
        db.ensure_schema().unwrap();

        let id = db
            .insert_message("sb_peer1".into(), "hello FFI".into(), 1000, true)
            .unwrap();
        assert_eq!(id, 1);

        let msgs = db.get_messages("sb_peer1".into()).unwrap();
        assert_eq!(msgs.len(), 1);
        assert_eq!(msgs[0].body, "hello FFI");

        let recent = db.get_recent_conversations(10).unwrap();
        assert_eq!(recent.len(), 1);

        let padded = db.pad_chaff(path.clone()).unwrap();
        assert!(padded > 0);

        let count = db.chaff_count().unwrap();
        assert_eq!(count, padded);

        assert!(db.delete_message(id).unwrap());
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn invite_ffi_flow() {
        let key = vec![42u8; 32];
        let key_arr: [u8; 32] = key.clone().try_into().unwrap();
        let queue_id = silentbell_p2p::QueueId::from_public_key(&key_arr);
        let queue = queue_id.as_bytes().to_vec();

        let invite = create_invite(key.clone(), queue, Some("Alice".into())).unwrap();
        assert!(invite.account_id.starts_with("sb_"));
        assert!(invite_validate(FfiInvitePayload {
            account_id: invite.account_id.clone(),
            public_key_b58: invite.public_key_b58.clone(),
            queue_id_b58: invite.queue_id_b58.clone(),
            display_name: invite.display_name.clone(),
            version: invite.version,
        })
        .unwrap());

        let uri = invite_to_uri(FfiInvitePayload {
            account_id: invite.account_id.clone(),
            public_key_b58: invite.public_key_b58.clone(),
            queue_id_b58: invite.queue_id_b58.clone(),
            display_name: invite.display_name.clone(),
            version: invite.version,
        })
        .unwrap();
        assert!(uri.starts_with("sofamsg://connect?"));

        let parsed = invite_from_uri(uri).unwrap();
        assert_eq!(parsed.display_name, Some("Alice".to_string()));

        let qr_data = invite_to_qr_data(parsed).unwrap();
        let from_qr = invite_from_qr_data(qr_data).unwrap();
        assert_eq!(from_qr.display_name, Some("Alice".to_string()));

        let q_id = derive_queue_id(key).unwrap();
        assert_eq!(q_id, from_qr.queue_id_b58);
    }
}
